insert into subjects values ("0606", "IGCSE Additional Mathematics");
insert into subjects values ("0607", "IGCSE International Mathematics");
insert into subjects values ("0460", "IGCSE Geography");
insert into subjects values ("0475", "IGCSE Literature in English");
insert into subjects values ("0500", "IGCSE First Language English");
insert into subjects values ("0478", "IGCSE Computer Science");
insert into subjects values ("ZKPHY", "ZK Physics");
insert into subjects values ("YKPSMATH", "YKPS Mathematics");
insert into subjects values ("0610", "IGCSE Biology");
insert into subjects values ("0620", "IGCSE Chemistry");
insert into subjects values ("0625", "IGCSE Physics");
insert into subjects values ("0450", "IGCSE Business Studies");
insert into subjects values ("0455", "IGCSE Economics");
insert into subjects values ("0413", "IGCSE Physical Education");
insert into subjects values ("IBBIO", "IB Biology");
insert into subjects values ("IBPSY", "IB Psychology");
insert into subjects values ("IBSEHS", "IB Sports, Exercise, and Health Science");
insert into subjects values ("0509", "IGCSE First Language Chinese");
insert into subjects values ("IBCHN", "IB Chinese Language and Literature");
insert into subjects values ("EXTBIO", "External Biology");
insert into subjects values ("IBTOK", "IB Theory of Knowledge");
insert into subjects values ("IBEE", "IB Extended Essay");
insert into subjects values ("IBPHIL", "IB Philosophy");
