INSERT INTO subjects VALUES("0606", "IGCSE Additional Mathematics");
INSERT INTO subjects VALUES("0607", "IGCSE International Mathematics");
INSERT INTO subjects VALUES("0460", "IGCSE Geography");
INSERT INTO subjects VALUES("0470", "IGCSE History");
INSERT INTO subjects VALUES("0475", "IGCSE Literature in English");
INSERT INTO subjects VALUES("0500", "IGCSE First Language English");
INSERT INTO subjects VALUES("0478", "IGCSE Computer Science");
INSERT INTO subjects VALUES("ZKPHY", "ZK Physics");
INSERT INTO subjects VALUES("YKPSMATH", "YKPS Mathematics");
INSERT INTO subjects VALUES("0610", "IGCSE Biology");
INSERT INTO subjects VALUES("0620", "IGCSE Chemistry");
INSERT INTO subjects VALUES("0625", "IGCSE Physics");
INSERT INTO subjects VALUES("0450", "IGCSE Business Studies");
INSERT INTO subjects VALUES("0455", "IGCSE Economics");
INSERT INTO subjects VALUES("0413", "IGCSE Physical Education");
INSERT INTO subjects VALUES("IBBIO", "IB Biology");
INSERT INTO subjects VALUES("IBPSY", "IB Psychology");
INSERT INTO subjects VALUES("IBSEHS", "IB Sports, Exercise, and Health Science");
INSERT INTO subjects VALUES("0509", "IGCSE First Language Chinese");
INSERT INTO subjects VALUES("IBCHN", "IB Chinese Language and Literature");
INSERT INTO subjects VALUES("EXTBIO", "External Biology");
INSERT INTO subjects VALUES("IBTOK", "IB Theory of Knowledge");
INSERT INTO subjects VALUES("IBEE", "IB Extended Essay");
INSERT INTO subjects VALUES("IBPHIL", "IB Philosophy");
INSERT INTO subjects VALUES("ZKCHM", "ZK Chemistry");
INSERT INTO subjects VALUES("ZKME", "ZK Moral Education");
INSERT INTO subjects VALUES("C4CGEO", "C4C Geography");
INSERT INTO subjects VALUES("C4CPOL", "C4C Politics");
INSERT INTO subjects VALUES("C4CHIS", "C4C History");
INSERT INTO subjects VALUES("ZKCHN", "ZK Chinese");
INSERT INTO subjects VALUES("IBCHM", "IB Chemistry");
INSERT INTO subjects VALUES("IBECN", "IB Economics");
INSERT INTO subjects VALUES("IBENGLAL", "IB English Language and Literature");
INSERT INTO subjects VALUES("IBENGLIT", "IB English Literature");
INSERT INTO subjects VALUES("IBMATH", "IB Mathematics");
INSERT INTO subjects VALUES("IBPHY", "IB Physics");
INSERT INTO subjects VALUES("0410", "IGCSE Music");
INSERT INTO subjects VALUES("IBGEO", "IB Geography");
INSERT INTO subjects VALUES("IBHIS", "IB History");
INSERT INTO subjects VALUES("IBESS", "IB Environmental Systems and Societies");
